# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['localhost:9182']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['localhost:9216']

  - job_name: 'fastapi_metrics'
    static_configs:
      - targets: ['localhost:8000']
